security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_CLIENT: ROLE_CLIENT
        ROLE_CONSULTANT: ROLE_CONSULTANT
        ROLE_GESTIONNAIRE: ROLE_GESTIONNAIRE
        ROLE_CHEF: ROLE_CHEF


    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                remember_me:  true
              #  csrf_token_generator: security.csrf.token_manager
              #  always_use_default_target_path: false
               # default_target_path:            tim_soft_client_homepage
                login_path: /login
            logout: 
                path: /logout
                target: /login
            anonymous:    ~

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/GestionUtilisateur/ConfirmationMailUtilisateur/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
     
    access_decision_manager:
        strategy: unanimous
        allow_if_all_abstain: false
