<?php

namespace TimSoft\BuBundle\Repository;

/**
 * BuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUsers($users)
    {
        $query = $this->createQueryBuilder('b')
            ->select('b')
            ->innerJoin('b.utilisateurs', 'u')
            ->addSelect('u')
            ->where('u IN (:users)')
            ->setParameter('users', $users)
            ->getQuery();
        return $query->getResult();
    }
}
