<?php

namespace TimSoft\TasksBundle\Repository;

/**
 * TaskEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskEventRepository extends \Doctrine\ORM\EntityRepository
{

}
