<?php

namespace TimSoft\TasksBundle\Repository;

/**
 * TaskEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskEventRepository extends \Doctrine\ORM\EntityRepository
{
    public function betweenDates($start, $end, $user)
    {
        return $this->createQueryBuilder('p')
            ->select('p')
            ->where('p.start BETWEEN :start AND :end')
            ->orWhere('p.end BETWEEN :start AND :end OR p.periodique = :periodique')
            ->setParameter('start', $start)
            ->setParameter('end', $end)
            ->setParameter('periodique', true)
            ->getQuery()
            ->getResult();
    }

    public function findByUser($user, $start, $end)
    {
        return $this->createQueryBuilder('p')
            ->select('p')
            ->where('p.start BETWEEN :start AND :end')
            ->orWhere('p.end BETWEEN :start AND :end OR p.periodique = :periodique')
            ->andWhere('p.utilisateur = :user')
            ->setParameter('user', $user)
            ->setParameter('periodique', true)
            ->setParameter('start', $start)
            ->setParameter('end', $end)
            ->getQuery()
            ->getResult();
    }

    public function findByClient($client, $start, $end, $user)
    {
        return $this->createQueryBuilder('p')
            ->select('p')
            ->where('p.start BETWEEN :start AND :end')
            ->orWhere('p.end BETWEEN :start AND :end OR p.periodique = :periodique')
            ->andWhere('p.client = :client')
            ->setParameter('client', $client)
            ->setParameter('start', $start)
            ->setParameter('end', $end)
            ->setParameter('periodique', true)
            ->getQuery()
            ->getResult();
    }

    public function findByUtilisateur($user)
    {
        return $this->createQueryBuilder('p')
            ->select('p')
//            ->where('p.start BETWEEN :start AND :end')
            ->andWhere('p.periodique = :periodique')
            ->andWhere('p.utilisateur = :user')
            ->setParameter('user', $user)
            ->setParameter('periodique', false)
            ->getQuery()
            ->getResult();
    }
}
