<?php

namespace TimSoft\NotificationBundle\Repository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository
{
//    //Toutes les notifications d'un utilisateur
//    public function NotificationUtilisateur($Utilisateur) {
//        
//        return $this->createQueryBuilder('l')
//                        ->select('l')
//                        ->where('l.personneNotifiee =  :Utilisateur')
//                        ->setParameter('Utilisateur', $Utilisateur)
//                        ->getQuery()
//                        ->getResult();
//    }

    //Toutes les notifications d'un utilisateur
    public function NotificationUtilisateurParVu($Vu, $Utilisateur)
    {

        return $this->createQueryBuilder('n')
            ->select('n')
            ->where('n.personneNotifiee =  :Utilisateur')
            ->andWhere('n.seen = :Vu')
            ->setParameter('Utilisateur', $Utilisateur)
            ->setParameter('Vu', $Vu)
            ->getQuery()
            ->getResult();
    }

    //Toutes les notifications d'un utilisateur
    public function NotificationUtilisateurTrie($Utilisateur)
    {

        return $this->createQueryBuilder('n')
            ->select('n')
            ->from('TimSoftGeneralBundle:NotificationUtilisateur', 'nu')
            ->where('nu.Notification = n.id')
            ->andWhere('nu.Utilisateur =  :Utilisateur')
            ->orderBy('n.date', 'DESC')
            ->setParameter('Utilisateur', $Utilisateur)
            ->getQuery()
            ->getResult();
    }

}
