services:
#    tim_soft_facture.example:
#        class: TimSoft\FactureBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
#    TimSoft\FactureBundle\Service\FileUploader:
 #       arguments:
 #           $targetDir: '%DossierFactures%'