<?php

namespace TimSoft\GeneralBundle\Repository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends \Doctrine\ORM\EntityRepository
{
    //Renvoi le nombre total de Client
    public function getNBClient()
    {

        return $this->createQueryBuilder('l')
            ->select('COUNT(l)')
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function getClients()
    {

        return $this->createQueryBuilder('c')
            ->select('c')
            ->getQuery()
            ->getResult();
    }

    /**
     * @param $name
     * @return mixed
     */
    public function getByName($name)
    {
        return $this->createQueryBuilder('c')
            ->select('c')
            ->where('c.raisonSociale =  :name ')
            ->setParameter('name', $name)
            ->getQuery()
            ->getFirstResult();
    }
}
