<?php

namespace TimSoft\GeneralBundle\Repository;

use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;
use DoctrineExtensions\Query\Mysql;

/**
 * DroitAccesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DroitAccesRepository extends \Doctrine\ORM\EntityRepository
{
//    public function getRoute($route)
    public function getID($Route)
    {
        try {
            return $this->createQueryBuilder('d')
                ->select('d.id')
                ->where('d.routeDroit =  :Route')
                ->setParameter('Route', $Route)
                ->getQuery()
                ->getSingleScalarResult();
        } catch (NoResultException $e) {
        } catch (NonUniqueResultException $e) {
        }
    }
    
    public function getAllDroit() 
    {
         return $this->createQueryBuilder('d')
                       ->select('d')
                        ->where('d.categorieDroit != :Droit')
             ->andWhere('d.technique != 1')
                        ->setParameter('Droit', 'Autre')
                        ->getQuery()
                        ->getResult();
    }
    
//    public function getAllDroit() 
//    {
//         return $this->createQueryBuilder('d')
//                       ->select('d.nomDroit , g.role ')
//                        ->from('TimSoftGeneralBundle:DroitAccesGroupe', 'g')
//                        ->leftJoin('g.droit','WITH', 'd.id')
//                        ->where('g.droit = d.id')
//                        ->getQuery()
//                        ->getResult();
//    }
    
//     public function getAllDroitGroupePersonne() 
//    {
//        return $this->createQueryBuilder('d')
//                       ->select('d.nomDroit , g.role , p.roleUtilisateur')
//                        ->from('TimSoftGeneralBundle:DroitAccesGroupe g', 'TimSoftGeneralBundle:DroitAccesPersonne p')
//                        ->leftJoin('g.droit','WITH', 'd.id')
//                        ->leftJoin('p.droit','WITH', 'd.id')
//                        ->where('g.droit = d.id')
//                        ->andWhere('p.droit = d.id')
//                        ->getQuery()
//                        ->getResult();
//    }
    
//     public function getAllDroitUtilisateur() 
//    {
//        return $this->createQueryBuilder('d')
//                       ->select('d')
//                        ->from('TimSoftGeneralBundle:DroitAccesGroupe g', 'TimSoftGeneralBundle:DroitAccesPersonne p')
//                        ->where('d.id = 1')
////                        ->andWhere('p.droit = d.id')
//                        ->getQuery()
//                        ->getResult();
//    }
    
}
