<?php

namespace TimSoft\GeneralBundle\Repository;

/**
 * FichierJoinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FichierJoinRepository extends \Doctrine\ORM\EntityRepository
{
}
