<?php

namespace TimSoft\GeneralBundle\Repository;

/**
 * NotificationUtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationUtilisateurRepository extends \Doctrine\ORM\EntityRepository
{
}
